---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  lint: |
    set -e
    flake8
    ansible-lint
    yamllint .
verifier:
  name: ansible
  log: true

